package ecdsa

import "github.com/allocz/secp256k1/internal/dcrsecp"

// PutRS puts sig.r and sig.s values inside rOut and sOut.
func (sig *Signature) PutRS(rOut, sOut *secp256k1.ModNScalar) {
	*rOut, *sOut = sig.r, sig.s
}

// SetRS sets sig.r and sig.s values to r and s.
func (sig *Signature) SetRS(r, s *secp256k1.ModNScalar) {
	sig.r, sig.s = *r, *s
}

// signZeroAlloc generates an ECDSA signature over the secp256k1 curve for the
// provided hash (which should be the result of hashing a larger message) using
// the given nonce and private key and returns it along with an additional
// public key recovery code and success indicator.  Upon success, the produced
// signature is deterministic (same message, nonce, and key yield the same
// signature) and canonical in accordance with BIP0062.
//
// Note that signRFC6979 makes use of this function as it is the primary ECDSA
// signing logic.  It differs in that it accepts a nonce to use when signing and
// may not successfully produce a valid signature for the given nonce.  It is
// primarily separated for testing purposes.
func signZeroAlloc(sigOut *Signature, privKey, nonce *secp256k1.ModNScalar,
	hash []byte) (byte, bool) {

	// The algorithm for producing an ECDSA signature is given as algorithm 4.29
	// in [GECC].
	//
	// The following is a paraphrased version for reference:
	//
	// G = curve generator
	// N = curve order
	// d = private key
	// m = message
	// r, s = signature
	//
	// 1. Select random nonce k in [1, N-1]
	// 2. Compute kG
	// 3. r = kG.x mod N (kG.x is the x coordinate of the point kG)
	//    Repeat from step 1 if r = 0
	// 4. e = H(m)
	// 5. s = k^-1(e + dr) mod N
	//    Repeat from step 1 if s = 0
	// 6. Return (r,s)
	//
	// This is slightly modified here to conform to RFC6979 and BIP 62 as
	// follows:
	//
	// A. Instead of selecting a random nonce in step 1, use RFC6979 to generate
	//    a deterministic nonce in [1, N-1] parameterized by the private key,
	//    message being signed, and an iteration count for the repeat cases
	// B. Negate s calculated in step 5 if it is > N/2
	//    This is done because both s and its negation are valid signatures
	//    modulo the curve order N, so it forces a consistent choice to reduce
	//    signature malleability

	// NOTE: Step 1 is performed by the caller.
	//
	// Step 2.
	//
	// Compute kG
	//
	// Note that the point must be in affine coordinates.
	k := nonce
	var kG secp256k1.JacobianPoint
	secp256k1.ScalarBaseMultNonConst(k, &kG)
	kG.ToAffine()

	// Step 3.
	//
	// r = kG.x mod N
	// Repeat from step 1 if r = 0
	r, overflow := fieldToModNScalar(&kG.X)
	if r.IsZero() {
		return 0, false
	}

	// Since the secp256k1 curve has a cofactor of 1, when recovering a
	// public key from an ECDSA signature over it, there are four possible
	// candidates corresponding to the following cases:
	//
	// 1) The X coord of the random point is < N and its Y coord even
	// 2) The X coord of the random point is < N and its Y coord is odd
	// 3) The X coord of the random point is >= N and its Y coord is even
	// 4) The X coord of the random point is >= N and its Y coord is odd
	//
	// Rather than forcing the recovery procedure to check all possible
	// cases, this creates a recovery code that uniquely identifies which of
	// the cases apply by making use of 2 bits.  Bit 0 identifies the
	// oddness case and Bit 1 identifies the overflow case (aka when the X
	// coord >= N).
	//
	// It is also worth noting that making use of Hasse's theorem shows
	// there are around log_2((p-n)/p) ~= -127.65 ~= 1 in 2^127 points where
	// the X coordinate is >= N.  It is not possible to calculate these
	// points since that would require breaking the ECDLP, but, in practice
	// this strongly implies with extremely high probability that there are
	// only a few actual points for which this case is true.
	pubKeyRecoveryCode := byte(overflow<<1) | byte(kG.Y.IsOddBit())

	// Step 4.
	//
	// e = H(m)
	//
	// Note that this actually sets e = H(m) mod N which is correct since
	// it is only used in step 5 which itself is mod N.
	var e secp256k1.ModNScalar
	e.SetByteSlice(hash)

	// Step 5 with modification B.
	//
	// s = k^-1(e + dr) mod N
	// Repeat from step 1 if s = 0
	// s = -s if s > N/2
	kinv := new(secp256k1.ModNScalar).InverseValNonConst(k)
	var s secp256k1.ModNScalar
	s.Mul2(privKey, &r).Add(&e).Mul(kinv)
	if s.IsZero() {
		return 0, false
	}
	if s.IsOverHalfOrder() {
		s.Negate()

		// Negating s corresponds to the random point that would have been
		// generated by -k (mod N), which necessarily has the opposite
		// oddness since N is prime, thus flip the pubkey recovery code
		// oddness bit accordingly.
		pubKeyRecoveryCode ^= 0x01
	}

	// Step 6.
	//
	// Return (r,s)
	sigOut.r = r
	sigOut.s = s
	return pubKeyRecoveryCode, true
}

// signRFC6979ZeroAlloc generates a deterministic ECDSA signature according to
// RFC6979 and BIP0062 and returns it along with an additional public key
// recovery code for efficiently recovering the public key from the signature.
func signRFC6979ZeroAlloc(sigOut *Signature, privKey *secp256k1.PrivateKey,
	hash []byte) byte {

	// The algorithm for producing an ECDSA signature is given as algorithm
	// 4.29 in [GECC].
	//
	// The following is a paraphrased version for reference:
	//
	// G = curve generator
	// N = curve order
	// d = private key
	// m = message
	// r, s = signature
	//
	// 1. Select random nonce k in [1, N-1]
	// 2. Compute kG
	// 3. r = kG.x mod N (kG.x is the x coordinate of the point kG)
	//    Repeat from step 1 if r = 0
	// 4. e = H(m)
	// 5. s = k^-1(e + dr) mod N
	//    Repeat from step 1 if s = 0
	// 6. Return (r,s)
	//
	// This is slightly modified here to conform to RFC6979 and BIP 62 as
	// follows:
	//
	// A. Instead of selecting a random nonce in step 1, use RFC6979 to
	//    generate a deterministic nonce in [1, N-1] parameterized by the
	//    private key, message being signed, and an iteration count for the
	//    repeat cases
	// B. Negate s calculated in step 5 if it is > N/2
	//    This is done because both s and its negation are valid signatures
	//    modulo the curve order N, so it forces a consistent choice to
	//    reduce signature malleability

	privKeyScalar := &privKey.Key
	var privKeyBytes [32]byte
	privKeyScalar.PutBytes(&privKeyBytes)
	defer zeroArray32(&privKeyBytes)
	for iteration := uint32(0); ; iteration++ {
		// Step 1 with modification A.
		//
		// Generate a deterministic nonce in [1, N-1] parameterized by
		// the private key, message being signed, and iteration count.
		var k secp256k1.ModNScalar
		secp256k1.NonceRFC6979ZeroAlloc(&k, privKeyBytes[:], hash, nil,
			nil, iteration)

		// Steps 2-6.
		pubKeyRecoveryCode, success := signZeroAlloc(sigOut,
			privKeyScalar, &k, hash)
		k.Zero()
		if !success {
			continue
		}

		return pubKeyRecoveryCode
	}
}

// SignZeroAlloc generates an ECDSA signature over the secp256k1 curve for the
// provided hash (which should be the result of hashing a larger message) using
// the given private key. The produced signature is deterministic (same message
// and same key yield the same signature) and canonical in accordance with
// RFC6979 and BIP0062.
func SignZeroAlloc(sigOut *Signature, key *secp256k1.PrivateKey,
	hash []byte) {

	signRFC6979ZeroAlloc(sigOut, key, hash)
}
