package secp256k1

import (
	"math/rand"
	"testing"
)

// randFieldVal returns a field value created from a random value generated by
// the passed rng.
func randFieldVal(t *testing.T, rng *rand.Rand) *FieldVal64 {
	t.Helper()

	var buf [32]byte
	if _, err := rng.Read(buf[:]); err != nil {
		t.Fatalf("failed to read random: %v", err)
	}

	// Create and return a field value.
	var fv FieldVal64
	fv.SetBytes(&buf)
	fv.Normalize()
	return &fv
}

// mustFieldValWithOverflow converts the passed hex string into a [FieldVal64] and
// will panic if there is an error.  Values that overflow are NOT treated as an
// error.
//
// This is only provided for the hard-coded constants so errors in the source
// code can be detected. It will only (and must only) be called with hard-coded
// values.
func mustFieldValWithOverflow(s string) *FieldVal64 {
	return mustFieldValInternal(s, true)
}
